task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("django.contrib.auth.urls")),
    path("", include("tasks.urls")),
    path("users/", include("users.urls")),
]

tasks/urls.py
from django.urls import path

from tasks import views


app_name = "tasks"

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
]

users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("", views.List.as_view(), name="list"),
    path("create/", views.Create.as_view(), name="create"),
    path("<int:user_id>/update/", views.Update.as_view(), name="update"),
    path("<int:user_id>/delete/", views.Delete.as_view(), name="delete"),
]

users/models.py
from django.db import models

# Create your models here.

tasks/views.py
from django.shortcuts import render
from django.views import View


class Index(View):
    template_name = "tasks/index.html"

    def get(self, request):
        return render(request, self.template_name)

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import View


class Create(View):
    template_name = "registration/create.html"

    def get(self, request):
        return render(request, self.template_name, context={"form": UserCreationForm()})

    def post(self, request):
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("login")
        else:
            return render(request, self.template_name, context={"form": form})


class Update(LoginRequiredMixin, View):
    login_url = "login"
    template_name = "users/update.html"

    def handle_no_permission(self):
        return redirect(self.login_url)

    def get(self, request, user_id):
        context = {"username": User.objects.get(id=user_id).username}
        return render(request, self.template_name, context=context)


class Delete(LoginRequiredMixin, View):
    login_url = "login"
    template_name = "users/delete.html"

    def handle_no_permission(self):
        return redirect(self.login_url)

    def get(self, request, user_id):
        context = {"user": User.objects.get(id=user_id)}
        return render(request, self.template_name, context=context)

    def post(self, request, user_id):
        user = User.objects.get(id=user_id)
        user.delete()
        return redirect("tasks:index")


class List(View):
    template_name = "users/list.html"

    def get(self, request):
        users = User.objects.all()
        context = {"users": users}
        return render(request, self.template_name, context=context)

tasks/templates/tasks/base.html
{% load i18n %}
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>{% trans "Task manager" %}</title>
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <a class="navbar-brand" href="{% url 'tasks:index' %}">
      {% trans "Task manager" %}</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:list' %}">
            {% trans "Users" %}
          </a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">{% trans "Hello" %}, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">{% trans "Log out" %}</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:create' %}">{% trans "Register" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">{% trans "Log in" %}</a>
          </li>
        {% endif %}
      </ul>

    </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 borde-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>
</html>

tasks/templates/tasks/index.html
{% extends "tasks/base.html" %}
{% load i18n %}

{% block page_header %}
  <h2>{% trans "Task manager" %}</h2>
{% endblock page_header %}

{% block content %}
<p>{% trans "index" %}</p>
{% endblock content %}

users/templates/users/delete.html
{% extends "tasks/base.html" %}
{% load i18n %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>{% trans "Delete account" %} {{ user.username }}</h2>
{% endblock page_header %}

{% block content %}
  <form method="post" action="{% url 'users:delete' user.id %}" class="form">
    {% csrf_token %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">{% trans "delete" %}</button>
    {% endbuttons %}
  </form>
{% endblock content %}

users/templates/users/list.html
{% extends "tasks/base.html" %}
{% load i18n %}

{% block page_header %}
  <h2>{% trans "User list" %}</h2>
{% endblock page_header %}

{% block content %}
<table class="table table-hover mx-auto my-5">
    <thead class="thead-light">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">{% trans "username" %}</th>
            <th scope="col">{% trans "fullname" %}</th>
            <th scope="col">{% trans "creation_date" %}</th>
            <th scope="col">{% trans "edit_buttons" %}</th>
        </tr>
    </thead>

    <tbody>
        {% for user in users %}
        <tr>
            <td scope="row">{{ user.id }}</td>
            <td scope="row">{{ user.username }}</td>
            <td>{{ user.get_full_name }}</td>
            <td>{{ user.date_joined }}</td>
            <td>
                <a href="{% url 'users:update' user.id %}">{% trans "update" %}</a>
                <br>
                <a href="{% url 'users:delete' user.id %}">{% trans "delete" %}</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

users/templates/users/update.html
{% extends "tasks/base.html" %}
{% load i18n %}

{% block page_header %}
  <h2>{% trans "update_user_page" %} {{ username }}</h2>
{% endblock page_header %}

{% block content %}
{% endblock content %}

users/templates/users/users_list.html
{% extends "tasks/base.html" %}
{% load i18n %}

{% block page_header %}
  <h2>{% trans "User list" %}</h2>
{% endblock page_header %}

{% block content %}
<table class="table table-hover mx-auto my-5">
    <thead class="thead-light">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">{% trans "username" %}</th>
            <th scope="col">{% trans "fullname" %}</th>
            <th scope="col">{% trans "creation_date" %}</th>
            <th scope="col">{% trans "edit_buttons" %}</th>
        </tr>
    </thead>

    <tbody>
        {% for user in users %}
        <tr>
            <td scope="row">{{ user.id }}</td>
            <td scope="row">{{ user.username }}</td>
            <td>{{ user.get_full_name }}</td>
            <td>{{ user.date_joined }}</td>
            <td>
                <a href="{% url 'users:update' user.id %}">{% trans "update" %}</a>
                <br>
                <a href="{% url 'users:delete' user.id %}">{% trans "delete" %}</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}